<div class="plain">
	<h1>Damage Types</h1>
	
	<h3>Wind Damage</h3>
	
	<p>Wind damage is classified as creased or missing shingles. The negative and positive pressures that are applied to a dwelling due to wind gusts is the reason shingles will fail and crease or become dislodged. Shingles will usually fail first in the weakest spots, specifically at the un-bonded tabs where a seal strip has failed. Generally this occurs when wind speeds reach upwards of 60+ mph. The un-bonded seal strips alone are not considered wind damage, as other elements can contribute to the un-bonding of a seal strip. Seal strips tend to break down and release over time due to expansion and contraction of the roofing materials, inadequate sealant applied, and old age. Most shingle manufacturers only warranty the shingle seal strips for 5-10 years. Years ago shingles relied on their own weight to resist the wind and didn’t have any seal strips. New wind damage can be differentiated from old wind damage by looking at the color of the creasing. Creasing which has recently occurred will appear to be dark black, showing the freshness of the asphalt exposure. Old wind damage will start to weather and become the same shade of grey as the rest of the exposed asphalt on the shingle, thus dating the wind damage.</p>
	
	<h3>Hail Damage</h3>
	
	<p>The industry standards for Hail damage is specified as a loss in water shedding capability, or the reduction of the long term service life of the shingle. The damaging effects of Hail are based on many factors involved, IE: the size and density of the hailstone, the steepness or pitch of the roofs involved, the quality and age of the asphalt shingles, and direction and speed of the wind. Functional hail damage, when found on an asphalt shingle, appears to have a localized granular loss usually in a circular pattern. Upon further inspection of the localized granular loss there is usually a soft tenderness to the shingle surface, commonly referred to as bruising. The bruising is a result of the Hail severing the fiberglass mat which is between the layers of asphalt. This damage can be detected immediately after a hailstorm has occurred, and does not appear later. New hail damage can be differentiated from old hail damage by looking at the color of the asphalt exposure in the hail hit. A hail hit which has recently occurred will appear to be dark black, showing the freshness of the asphalt exposure. Old hail damage will start to weather and become the same shade of grey as the rest of the exposed asphalt on the shingle, thus dating the hail damage. Granule loss that is often found in gutters and downspout run off does not indicate that hail has damaged the asphalt roofing system. Widespread granule loss is common and is a result of normal weathering, and the aging process. Granules may become dislodged due to wind, heavy rainfall, small hailstorms, and normal foot traffic. This widespread granule loss does not affect the long term service life or the water shedding capability of your asphalt roofing system. There are also other signs that we check for that validate the size of the hail, and how recently the hailstorm has occurred. The telltale signs left by a hailstorm are the spatter marks. Spatter marks are left behind in the algae growth on the roof and in various other spots on the house where it takes the oxidation off. Soft metal damage is another sign that a hailstorm has occurred on the roofing system. When hailstones get big and dense enough they can damage the soft metal vents that protrude through the roof. Again, even with spatter marks, and soft metal damage, you can still have no damage to you asphalt shingles. Newer asphalt shingles withstand a greater level of impact, and require more force to damage the fiberglass matting then older shingles that have been subjected to the UV rays of the sun and other weathering elements.</p>
</div>